package Query2Steps;/* Generated By:JavaCC: Do not edit this line. Query2StepsConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Query2StepsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int DROP = 7;
  /** RegularExpression Id. */
  int SELECT = 8;
  /** RegularExpression Id. */
  int INSERT = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int EQUALS = 15;
  /** RegularExpression Id. */
  int NOTEQUAL = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int NUM = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"create\"",
    "\"table\"",
    "\"drop\"",
    "\"select\"",
    "\"insert\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "<ID>",
    "<NUM>",
    "\";\"",
  };

}
