/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 7.0.10 */
public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=5105281436f88df78b978ed4f04e6606 (do not edit this line) */
